language: node_js
node_js:
  - "6"
  - "6.1"
  - "5"
  - "5.11"
  - "5.10"
  - "5.9"
  - "4"
  - "4.4"
  - "4.3"
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.6"
  - "node"
  - "iojs"

branches:
  only:
    - master

script:
  - npm test